name: Test E2E

on:
  pull_request:
  workflow_dispatch:

jobs:
  # Run e2e tests against a local L1 and L2 node
  l1-l2:
    name: L1 + L2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up the local node
        uses: OffchainLabs/actions/run-nitro-test-node@main
        with:
          nitro-testnode-ref: release

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: yarn
      - run: cp .env.example .env && yarn test:e2e

  # Run e2e tests against a local L1, L2, and L3 node with ETH fees
  # l1-l2-l3:
  #   name: L1 + L2 + L3
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18

  #     - name: Set up the local node
  #       uses: OffchainLabs/actions/run-nitro-test-node@main
  #       with:
  #         nitro-testnode-ref: release
  #         l3-node: true

  #     - name: Install Foundry
  #       uses: foundry-rs/foundry-toolchain@v1
  #       with:
  #         version: nightly

  #     - run: yarn
  #     - run: cp .env.example .env && yarn test:e2e

  # Run e2e tests against a local L1, L2, and L3 node with ERC20 fees
  # l1-l2-l3-erc20:
  #   name: L1 + L2 + L3 with ERC20 fees
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18

  #     - name: Set up the local node
  #       uses: OffchainLabs/actions/run-nitro-test-node@main
  #       with:
  #         nitro-testnode-ref: release
  #         l3-node: true
  #         args: --l3-fee-token

  #     - name: Install Foundry
  #       uses: foundry-rs/foundry-toolchain@v1
  #       with:
  #         version: nightly

  #     - run: yarn
  #     - run: cp .env.example .env && yarn test:e2e
